pipeline {
    agent none
    stages {
        stage ('Deploy') {
            agent {
                    node {
                        label 'master'
                    }
                }
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    sh '/var/jenkins_home/scripts/fibonacci.sh 5'
                }
            }
        }
        stage ('Build') {
            agent {
                    node {
                        label 'agent'
                    }
                }
            steps {
            timeout(time: 1, unit: 'MINUTES') {
                    sh '/var/jenkins_home/scripts/fibonacci.sh 32'
                }
            }
        }
    }
}
