pipeline {
    agent none
    stages {
        stage ('Deploy') {
            agent {
                    node {
                        label 'master'
                    }
                }
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    sh '/var/jenkins_home/scripts/fibonacci.sh 1'
                }
            }
        }
        stage ('Build') {
            agent {
                    docker {
                        image 'alpine:latest'
                    }
                }
            steps {
                    sh 'node --version'
                }
            }
        }
    }

