pipeline {
    agent 'agent'
    stages {
        stage('Hello') {
            steps {
                sh 'echo "Hello World!"'
            }
        }
        stage('Content') {
            steps {
                sh '''
                    echo "It's multiline"
                    cd /var/jenkins_home
                    ls -lah
                    date
                '''
            }
        }
    }
}
