pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello World!"'
                sh '''
                    echo "It's multiline"
                    cd /var/jenkins_home
                    ls -lah
                '''
            }
        }
    }
}