pipeline {
    agent any
    parameters {
        string(name: 'Greeting', defaultValue:'Hello', description: 'How should I greet the World?')
    }
    stages {
        stage('Example') {
            steps {
                echo "${params.Greeting} World!"
            }
        }
    }
}